### PR TITLE
Uploaded Vending Machine, Target and bird models + bird animation

### PR DESCRIPTION
**Pull request by jbeccherini**
Added vending machine, target and bird models & set up bird animations

### CODE REVIEW

**Review by Aether700 — COMMENTED** [review]
Everything looks good but can you provide an animation for the birds when they are at rest. Maybe have them with their wings folded if possible?

**Comment by Aether700** [comment]
image
here is what I had in mind for the folded wing

**Comment by jbeccherini** [comment]
Bird is in Ai Test scene and idles until the starts flying trigger is called

**Review by Aether700 — APPROVED** [review]
good job

**Pull request merged**
