### PR TITLE
AI now uses custom physics

### PR DESCRIPTION
**Pull request by afourneaux**
Applied player physics to AI so they bump gaily around before returning to the track

### CODE REVIEW

**Review by Aether700 — COMMENTED** [review]
Looking good, do the birds also use the custom physics?

**Comment by Aether700** [comment]
Also, when testing other prs I've noticed that sometimes the player can glitch through the ceiling or through the level if you get stuck in it for long enough. Any idea why or how to fix it?

**Comment by afourneaux** [comment]
- Birds do not use custom physics, and I don't think we'd gain much by swapping them over since they're meant to be the bullies rather than the bullied
- The 3D meshes are unfortunately flat, so I can't add volume to their hitboxes and prevent fast objects from passing through, even with continuous collisions. I'm not sure of a quick fix for the levels, but we could just lower the player's speed a touch. Currently, the dumpster and portapotty should be slow enough to not break through, but I've been practicing to hide this flaw during the demo just in case

**Comment by Aether700** [comment]
> * Birds do not use custom physics, and I don't think we'd gain much by swapping them over since they're meant to be the bullies rather than the bullied
> * The 3D meshes are unfortunately flat, so I can't add volume to their hitboxes and prevent fast objects from passing through, even with continuous collisions. I'm not sure of a quick fix for the levels, but we could just lower the player's speed a touch. Currently, the dumpster and portapotty should be slow enough to not break through, but I've been practicing to hide this flaw during the demo just in case

Sounds good. If you think we should lower the speed of the racers I'm ok with that

**Review by Aether700 — APPROVED** [review]
Good work

**Pull request merged**
